In [3]:
from google.colab import files
uploaded = files.upload()

Saving ad_10000records.csv to ad_10000records.csv

In [181]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
df=pd.read_csv("ad_10000records.csv")
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [182]:
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Gender,Country,Timestamp,Clicked on Ad
0,62.26,32.0,69481.85,172.83,Decentralized real-time circuit,Lisafort,Male,Svalbard & Jan Mayen Islands,2016-06-09 21:43:05,0
1,41.73,31.0,61840.26,207.17,Optional full-range projection,West Angelabury,Male,Singapore,2016-01-16 17:56:05,0
2,44.40,30.0,57877.15,172.83,Total 5thgeneration standardization,Reyesfurt,Female,Guadeloupe,2016-06-29 10:50:45,0
3,59.88,28.0,56180.93,207.17,Balanced empowering success,New Michael,Female,Zambia,2016-06-21 14:32:32,0
4,49.21,30.0,54324.73,201.58,Total 5thgeneration standardization,West Richard,Female,Qatar,2016-07-21 10:54:35,1

In [183]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Gender,Country,Timestamp
7235,67.56,39.0,60638.38,124.44,Cloned object-oriented benchmark,Westshire,Female,Australia,2016-05-31 09:06:29
8743,53.92,39.0,54755.71,154.74,User-friendly client-server instruction set,North Raymond,Male,Bosnia and Herzegovina,2016-01-23 17:39:06
4261,56.30,27.0,36884.23,131.29,Decentralized needs-based analyzer,Jordantown,Male,New Zealand,2016-03-23 21:06:51
1970,55.60,24.0,52252.91,182.20,Up-sized 6thgeneration moratorium,Garciaside,Female,El Salvador,2016-01-12 21:17:15
7401,40.17,26.0,68030.18,228.78,Persistent even-keeled application,East Kevinbury,Male,Puerto Rico,2016-03-11 06:49:10

In [184]:
x_temp_train = x_train.copy()
x_temp_train["target"] = y_train

country_enc_train = x_temp_train.groupby("Country")["target"].mean()
x_train["Country"] = x_train["Country"].map(country_enc_train)

city_enc_train = x_temp_train.groupby("City")["target"].mean()
x_train["City"] = x_train["City"].map(city_enc_train)

topic_enc_train = x_temp_train.groupby("Ad Topic Line")["target"].mean()
x_train["Ad Topic Line"] = x_train["Ad Topic Line"].map(topic_enc_train)


x_temp_test = x_test.copy()
x_temp_test["target"] = y_test

country_enc_test = x_temp_test.groupby("Country")["target"].mean()
x_test["Country"] = x_test["Country"].map(country_enc_test)

city_enc_test = x_temp_test.groupby("City")["target"].mean()
x_test["City"] = x_test["City"].map(city_enc_test)

topic_enc_test = x_temp_test.groupby("Ad Topic Line")["target"].mean()
x_test["Ad Topic Line"] = x_test["Ad Topic Line"].map(topic_enc_test)

In [185]:
x_train["Timestamp"]=pd.to_datetime(x_train["Timestamp"])
x_train["year"]=x_train["Timestamp"].dt.year
x_train["month"]=x_train["Timestamp"].dt.month
x_train["day"]=x_train["Timestamp"].dt.day
x_train["hour"]=x_train["Timestamp"].dt.hour
x_train["minute"]=x_train["Timestamp"].dt.minute
x_train["second"]=x_train["Timestamp"].dt.second
x_train = x_train.drop(columns=["Timestamp"])
male_female={
    "Male":1,
    "Female":2
}
#x_train["Gender"]=x_train["Gender"].map(male_female)
x_train=pd.get_dummies(x_train,columns=["Gender"])
x_train.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Country,year,month,day,hour,minute,second,Gender_Female,Gender_Male
7235,67.56,39.0,60638.38,124.44,1.000000,0.942857,0.838608,2016,5,31,9,6,29,True,False
8743,53.92,39.0,54755.71,154.74,0.117647,0.500000,0.670103,2016,1,23,17,39,6,False,True
4261,56.30,27.0,36884.23,131.29,0.000000,0.108108,0.400000,2016,3,23,21,6,51,False,True
1970,55.60,24.0,52252.91,182.20,0.615385,0.529412,0.896907,2016,1,12,21,17,15,True,False
7401,40.17,26.0,68030.18,228.78,0.000000,0.297872,0.200000,2016,3,11,6,49,10,False,True

In [186]:
x_test["Timestamp"] = pd.to_datetime(x_test["Timestamp"])

x_test["year"] = x_test["Timestamp"].dt.year
x_test["month"] = x_test["Timestamp"].dt.month
x_test["day"] = x_test["Timestamp"].dt.day
x_test["hour"] = x_test["Timestamp"].dt.hour
x_test["minute"] = x_test["Timestamp"].dt.minute
x_test["second"] = x_test["Timestamp"].dt.second

x_test = x_test.drop(columns=["Timestamp"])

#x_test["Gender"] = x_test["Gender"].map(male_female)
x_test=pd.get_dummies(x_test,columns=["Gender"])
x_test.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Country,year,month,day,hour,minute,second,Gender_Female,Gender_Male
9499,81.75,33.0,61005.87,204.02,0.300000,0.400000,0.296296,2016,7,9,11,4,54,False,True
8645,53.92,28.0,59448.44,217.37,0.315789,0.230769,0.343750,2016,1,23,17,39,6,False,True
5435,75.42,35.0,42696.67,140.15,1.000000,1.000000,0.772727,2016,7,14,22,43,29,False,True
514,71.03,28.0,71222.40,217.37,0.352941,0.000000,0.625000,2016,7,15,15,43,36,True,False
56,76.64,31.0,56180.93,207.17,0.000000,0.142857,0.129032,2016,6,21,14,32,32,True,False

In [190]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [191]:
y_predict=model.predict(x_test)

In [192]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
cm

array([[930,  69],
       [ 60, 941]])